#fast image creation which avoids downloading all maven dependencies each time
#steps which are neded to execute before building an image:
#    mvn clean install
#    cd parecodistribution
#    ./prepareBuild.sh
#    cd -
FROM java:8-jre-alpine
COPY parecodistribution/target/pareco-distribution-bin .
ENTRYPOINT ["/bin/sh"]